### PR TITLE
Add initial board members

### PR DESCRIPTION
**Pull request by gheine**

### CODE REVIEW

**Comment by trenaman** [comment]
Looks good to me for the initial list. Presumably we'll be adding folk in a subsequent commit to get the right coverage across the teams?

**Comment by gheine** [comment]
Yes, sounds good. I guess we'll need to touch base with the teams that are not represented yet and ask them to nominate 2 representatives. And the teams that are already represented can nominate a second rep.

**Comment by trenaman** [comment]
@jkalluri - do we have someone from Donovan's team included?

**Comment by lgelfan** [comment]
@trenaman - we do not. I would recommend Donovan and/or Jacob Tadros.

On the FE side, I think it would be great to engage Slava more but maybe next round. If we want more FE representation (which I'm certainly for - just trying to be mindful of the total size), I would add Soraya.

**Comment by himanshu4141** [comment]
Making it final and merging.
 - All the new team leads on this for now and kick it off.
 - People with * in front of their name are required to attend this meeting everyweek.

**Pull request merged**
